version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    command: gunicorn contentgraph_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  celery_worker:
  build: .
  command: celery -A contentgraph_backend worker --loglevel=info
  volumes:
    - .:/app
  environment:
    - DJANGO_SETTINGS_MODULE=contentgraph_backend.settings
    - CELERY_BROKER_URL=redis://red-d80tr6flk1mc739u13t0:6379/0
  depends_on:
    - redis
    - db

volumes:
  postgres_data:
