# Generated by Django 6.0.1 on 2026-06-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['min_units']},
        ),
        migrations.RemoveField(
            model_name='apiusagecharge',
            name='api_type',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='api_type',
        ),
    ]
