# Generated by Django 6.0.1 on 2026-05-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key_features',
            field=models.JSONField(default=list),
        ),
    ]
