# Generated by Django 6.0.1 on 2026-05-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_product_key_features'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
