# Generated by Django 6.0.1 on 2026-05-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytaskmeta',
            name='task_meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.bulkjobitem'),
        ),
    ]
