# Generated by Django 6.0.1 on 2026-05-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_celerytaskmeta_task_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjobitem',
            name='row_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
