# Generated by Django 6.0.1 on 2026-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_bulkjobitem_row_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
