# Generated by Django 6.0.1 on 2026-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_bulkjob_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
