# Generated by Django 6.0.1 on 2026-05-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_tokenusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesult',
            name='secondary_keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
