"""
Django settings for contentgraph_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url
import ssl



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True) 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['contentgraph-backend.onrender.com',
                 'backend.contentgraph.io',
                 'app.contentgraph.io',
                 'localhost',
                 'contentgraph-ai-agent.onrender.com',
                 '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'rest_framework',
    'corsheaders',
    'anymail',
    'content',
    'django_celery_results',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

ROOT_URLCONF = 'contentgraph_backend.urls'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://app.contentgraph.io",  # exact match, no trailing slash
]

# ✅ Allow all HTTP methods
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]
# ✅ Allow these headers
CORS_ALLOW_HEADERS = [
    "Content-Type",
    "Authorization",
    "Accept",
    "X-CSRFToken",
]
# ✅ Allow cookies / auth credentials
CORS_ALLOW_CREDENTIALS = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'contentgraph_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True,  # 👈 Supabase requires SSL
    )
       
    
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
 'handlers': {
        # Print logs to terminal
        'console': {
            'class':     'logging.StreamHandler',
            'formatter': 'simple',
        },
        # Save logs to a file
        'file': {
            'class':     'logging.FileHandler',
            'filename':  'logs/django_errors.log',
            'formatter': 'verbose',
        },
    },
 'loggers': {
        # Django's internal logs
        'django': {
            'handlers':  ['console', 'file'],
            'level':     'INFO',
            'propagate': True,
        },
        # Your app's logs
        'users': {
            'handlers':  ['console', 'file'],
            'level':     'DEBUG',
            'propagate': False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL ='users.user'
EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT', cast=int)
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = env('EMAIL_USE_SSL', cast=bool, default=True)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', cast=bool, default=False)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
 
UPSTASH_REDIS_URL=env('UPSTASH_REDIS_URL')
UPSTASH_REDIS_REST_URL = env('UPSTASH_REDIS_REST_URL')
UPSTASH_REDIS_REST_TOKEN = env('UPSTASH_REDIS_REST_TOKEN')
FRONTEND_URL ='https://app.contentgraph.io'

RESEND_API_KEY=env('RESEND_API_KEY')
SERVICE_JWT_PRIVATE_KEY = env('SERVICE_JWT_PRIVATE_KEY').strip()
FASTAPI_SERVICE_URL     = env('FASTAPI_SERVICE_URL')
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET')



# settings.py
REDIS_URL = env("REDIS_URL")  # note: rediss:// not redis://

CELERY_BROKER_URL        = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND    = 'django-db'
CELERY_ACCEPT_CONTENT    = ["json"]
CELERY_TASK_SERIALIZER   = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE          = "UTC"

# CELERY_TASK_SOFT_TIME_LIMIT      = 270
# CELERY_TASK_TIME_LIMIT           = 300
# CELERY_RESULT_EXPIRES            = 300
# CELERY_TASK_ACKS_LATE            = True
# CELERY_TASK_REJECT_ON_WORKER_LOST = True

# # Critical for Upstash — prevents idle connection drops

# CELERY_BROKER_TRANSPORT_OPTIONS = {
#     'visibility_timeout': 3600,
#     'socket_keepalive': True,
#     'retry_on_timeout': True,
# }

# CELERY_TASK_ALWAYS_EAGER = True
# CELERY_RESULT_EXTENDED = True

# CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}
# CELERY_REDIS_BACKEND_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}

# CELERY_REDIS_BACKEND_HEALTH_CHECK_INTERVAL = 25

